
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.ldap.Rdn;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class F_XepLich extends javax.swing.JFrame {

    /**
     * Creates new form F_XepLich
     * 
     */
    Vector vheader=new Vector();
    Vector vdata=new Vector();
    connecttionSQLsever con;
    public F_XepLich() {
        initComponents();
        con=new connecttionSQLsever("MSI", "QL_BacSi", "sa","123");
        this.setLocationRelativeTo(null);
        this.setTitle("Xếp lịch trực bệnh viện");
        vheader.add("STT");
        vheader.add("Tên Bác Sĩ");
        vheader.add("Số Phòng");
        vheader.add("Ca");
        vheader.add("Ngày Trực");
        tb_lich.setModel(new DefaultTableModel(vdata,vheader));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_bs = new javax.swing.JButton();
        btn_off = new javax.swing.JButton();
        btn_off1 = new javax.swing.JButton();
        btn_off2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_lich = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        btn_bs.setBackground(new java.awt.Color(255, 255, 255));
        btn_bs.setIcon(new javax.swing.ImageIcon("D:\\Form\\images\\bs6.png")); // NOI18N
        btn_bs.setText("Bác Sĩ");
        btn_bs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bsActionPerformed(evt);
            }
        });

        btn_off.setBackground(new java.awt.Color(255, 255, 255));
        btn_off.setIcon(new javax.swing.ImageIcon("D:\\Form\\images\\off.png")); // NOI18N
        btn_off.setText("Off");
        btn_off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_offActionPerformed(evt);
            }
        });

        btn_off1.setBackground(new java.awt.Color(255, 255, 255));
        btn_off1.setIcon(new javax.swing.ImageIcon("D:\\Form\\images\\lich.png")); // NOI18N
        btn_off1.setText("Xếp Lịch");
        btn_off1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_off1ActionPerformed(evt);
            }
        });

        btn_off2.setBackground(new java.awt.Color(255, 255, 255));
        btn_off2.setIcon(new javax.swing.ImageIcon("D:\\Form\\images\\trash_bin_icon-icons.com_67981.png")); // NOI18N
        btn_off2.setText("Xóa");
        btn_off2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_off2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_bs, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_off, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211)
                .addComponent(btn_off1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btn_off2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_bs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(btn_off, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_off1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_off2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));

        tb_lich.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_lich);

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    JInternalFrame frmLogin;
    private void btn_bsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bsActionPerformed
        // TODO add your handling code here:
      try{
            if(frmLogin==null||frmLogin.isClosed())
            {
                frmLogin= new Input_by_keybord("Danh Sách Bác Sĩ " ,  true, true, true, true);  
                jDesktopPane1.add(frmLogin);
           
                frmLogin.setLocation(this.getWidth()/2 - frmLogin.getWidth()/2,(this.getHeight()-20)/2 - frmLogin.getHeight()/2 - 20);

                frmLogin.setVisible(true);
            }
            else 
                if( frmLogin.isVisible()==false){
                frmLogin.setVisible(true);
                frmLogin.setLocation(this.getWidth()/2 - frmLogin.getWidth()/2,(this.getHeight()-20)/2 - frmLogin.getHeight()/2 - 20);
            }
       
    }
    catch(Exception e){}     
    }//GEN-LAST:event_btn_bsActionPerformed
    JInternalFrame DK_off;
    private void btn_offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_offActionPerformed
        // TODO add your handling code here:
        try{
            if(DK_off==null||DK_off.isClosed())
            {
                DK_off= new dangkyoff("Đăng Kí Ngày Nghỉ " ,  true, true, true, true);  
                jDesktopPane1.add(DK_off);
           
                DK_off.setLocation(this.getWidth()/2 - DK_off.getWidth()/2,(this.getHeight()-20)/2 - DK_off.getHeight()/2 - 20);

                DK_off.setVisible(true);
            }
            else 
                if( DK_off.isVisible()==false){
                DK_off.setVisible(true);
                DK_off.setLocation(this.getWidth()/2 - DK_off.getWidth()/2,(this.getHeight()-20)/2 - DK_off.getHeight()/2 - 20);
            }
       
    }
    catch(Exception e){}    
    }//GEN-LAST:event_btn_offActionPerformed

    private void btn_off1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_off1ActionPerformed
        // TODO add your handling code here:
        DAO_lich a=new DAO_lich();
        a.statr_xepLich();
        loadata();
   
       
        
    }//GEN-LAST:event_btn_off1ActionPerformed

    private void btn_off2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_off2ActionPerformed
        // TODO add your handling code here:
        DAO_lich a=new DAO_lich();
        a.delete();
        loadata();
    }//GEN-LAST:event_btn_off2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void loadata(){
//        vdata.removeAllElements();
//        vdata=e.LayBacSI_vector();
//        tb_bs1.updateUI();
        java.sql.Statement stmt;
        vdata.removeAllElements();
        try {
            con.OpenConnection();
            stmt = con.GetConnect().createStatement();
            String sql = "select *from dbo.fu_XepLich()";
            ResultSet rs=stmt.executeQuery(sql);
            while(rs.next())
            {
                String stt=rs.getString("id");
                String ten=rs.getString("TenBS");
                String phongtruc=rs.getString("PhongTruc");
                String catruc=rs.getString("CaTruc");
                String ngaytruc=rs.getString("NgayTruc");
                Vector<String> v=new Vector<String>();
                v.add(stt);
                v.add(ten);
                v.add(phongtruc);     
                 v.add(catruc);
                v.add(ngaytruc);

                vdata.add(v);
                tb_lich.updateUI();
            }
            con.CloseConnection();
        } catch (SQLException ex) {
            Logger.getLogger(F_XepLich.class.getName()).log(Level.SEVERE, null, ex);
        }          
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_XepLich.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_XepLich.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_XepLich.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_XepLich.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_XepLich().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bs;
    private javax.swing.JButton btn_off;
    private javax.swing.JButton btn_off1;
    private javax.swing.JButton btn_off2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_lich;
    // End of variables declaration//GEN-END:variables
}
